### ISSUE TITLE
Convert README from rtf to some other format

### ISSUE THREAD

**Issue by cooljeanius** [zadr/TextEdit#2]
GitHub doesn't render rtf-formatted READMEs (which is on purpose apparently, according some other bug report that I can't find right now), so maybe it might be worthwhile to convert the README to some other format. You can try using `unrtf` to do this: https://www.gnu.org/software/unrtf/unrtf.html

**Comment by cooljeanius** [comment]
Actually wait nvm I found the other bug report I was thinking of: https://github.com/github/markup/issues/283

**Comment by AugustM** [comment]
The file IS available in "some other format", it's available as ReadMe.txt, which has everything except the font changes.

**Comment by cooljeanius** [comment]
well, ok, a format that GitHub's default README-viewer will pick up first before the rtf version, then.

**Comment by tempelmann** [comment]
I've done this here: https://github.com/tempelmann/TextEdit

**Comment by cooljeanius** [comment]
> I've done this here: [tempelmann/TextEdit](https://github.com/tempelmann/TextEdit)

OK, I see that the relevant commit is tempelmann/TextEdit@de20b86... I'd suggest submitting that as a PR here, but this repo seems old and unmaintained, so I think I'll just close this issue instead...
